package:
  name: xdatbus
  version: 0.0.93

source:
  git_url: https://github.com/jcwang587/xdatbus.git
  git_tag: v0.0.93

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ase
    - pymatgen
    - mdanalysis
    - ovito

test:
  imports:
    - xdatbus

about:
  home: https://xdatbus.readthedocs.io/en/latest/
  license: MIT
  license_file: ../LICENSE.md
  summary: 'A python toolkit for analyzing XDATCAR'

extra:
  recipe-maintainers:
    - jcwang587
