# This workflow will upload a package to Anaconda Cloud when manually triggered.

name: anaconda-publish

on:
  workflow_dispatch:
    inputs:
      publishToAnaconda:
        description: 'Publish to Anaconda?'
        required: true
        default: 'no'

permissions:
  contents: read

jobs:
  anaconda-publish:
    # Ensure the conditional checks the correct input.
    if: github.event.inputs.publishToAnaconda == 'yes' 

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pipx install poetry

    - name: Setup Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH
        conda config --set always_yes yes

    - name: Install conda-build and anaconda-client
      run: conda install conda-build anaconda-client -y

    - name: Set version in meta.yaml
      run: |
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
        sed -i "s/PACKAGE_VERSION/$VERSION/" conda/meta.yaml

    - name: Build Conda package
      run: conda build -c conda-forge --no-test conda/ --output-folder conda-out --no-plugins

    - name: Upload Conda package to Anaconda Cloud
      run: |
        anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload -u xdatbus conda-out/noarch/xdatbus-*.tar.bz2
