name: quarto-publish

on:
  workflow_dispatch:
    inputs:
      publishToQuarto:
        description: 'Publish to Quarto?'
        required: true
        default: 'no'

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Quarto
      run: |
        # Add the commands to install Quarto here
        # For example:
        # wget -qO- "https://github.com/quarto-dev/quarto-cli/releases/download/v1.0.0/quarto-1.0.0-linux-amd64.deb" | sudo dpkg -i -

    - name: Render Quarto Content
      run: |
        # Add the commands to render your Quarto project
        # For example:
        # quarto render /path/to/your/quarto/project

    - name: Publish to Quarto
      if: ${{ github.event.inputs.publishToQuarto == 'yes' }}
      run: |
        # Add your commands to publish to Quarto here
        # This could include pushing to a 'gh-pages' branch, or another publishing platform
        # For example, to copy the content to a directory named 'quarto_site':
        mkdir -p quarto_site
        cp -r _site/* quarto_site/
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add quarto_site/*
        git commit -m "Auto-publish Quarto site"
        git push origin HEAD:gh-pages  # or another branch